FROM python:3.9.12

COPY ./Maggie.py /app/
COPY ./requirements.txt /app/

WORKDIR /app/

RUN mkdir /app/General
RUN mkdir /app/Homer
RUN mkdir /app/Lisa

RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3", "Maggie.py" ]